# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: ["main", "develop", "features", "feature/*", "bugfix/*", "hotfix/*"]
  release:
    types:
      - published

jobs:
  sonar-cloud-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=${{ secrets.SONAR_CLOUD_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_CLOUD_ORGANIZATION }}
          projectBaseDir: .
  snyk-maven-analysis:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    needs: [sonar-cloud-analysis]
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=low
  maven-build:
    runs-on: ubuntu-latest
    needs: [snyk-maven-analysis]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests -DnvdApiKey=${{secrets.NVD_API_KEY}}

    - name: Upload 'exception-response-x.y.z.jar' Artifact
      uses: actions/upload-artifact@v4
      with:
        name: exception-response
        path: target/*.jar
        compression-level: 0
        overwrite: true

    - name: Upload 'dependency-check-report.html' File
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html
        compression-level: 0
        overwrite: true

    - name: Publish to GitHub Packages Apache Maven
      if: github.event.action == 'published'
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
